# Generated by Django 3.0.5 on 2020-06-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hostel_block',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='patient',
            name='room_number',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='patient',
            name='suit_number',
            field=models.CharField(default='', max_length=40),
        ),
    ]
